visionData = [
    (
        "Pants",
        {
            "labels": [
                {
                    "mid": "/m/035r7c",
                    "description": "Leg",
                    "score": 0.91309464,
                    "topicality": 0.91309464,
                },
                {
                    "mid": "/m/0hgn_pr",
                    "description": "Active pants",
                    "score": 0.896606,
                    "topicality": 0.896606,
                },
                {
                    "mid": "/m/062581",
                    "description": "Sleeve",
                    "score": 0.87245,
                    "topicality": 0.87245,
                },
                {
                    "mid": "/m/0244x1",
                    "description": "Gesture",
                    "score": 0.85260487,
                    "topicality": 0.85260487,
                },
                {
                    "mid": "/m/031974",
                    "description": "Waist",
                    "score": 0.84093636,
                    "topicality": 0.84093636,
                },
                {
                    "mid": "/m/01j04m",
                    "description": "Thigh",
                    "score": 0.84039134,
                    "topicality": 0.84039134,
                },
                {
                    "mid": "/m/019swr",
                    "description": "Knee",
                    "score": 0.82812643,
                    "topicality": 0.82812643,
                },
                {
                    "mid": "/m/025xryy",
                    "description": "Sportswear",
                    "score": 0.8220613,
                    "topicality": 0.8220613,
                },
                {
                    "mid": "/m/0hgr6",
                    "description": "Denim",
                    "score": 0.7691811,
                    "topicality": 0.7691811,
                },
                {
                    "mid": "/m/02vwbzz",
                    "description": "Electric blue",
                    "score": 0.738484,
                    "topicality": 0.738484,
                },
            ],
            "objects": {},
            "logos": {},
        },
    ),
    (
        "Top",
        {
            "labels": [
                {
                    "mid": "/m/01dvt1",
                    "description": "Joint",
                    "score": 0.9755143,
                    "topicality": 0.9755143,
                },
                {
                    "mid": "/m/0dzf4",
                    "description": "Arm",
                    "score": 0.94543207,
                    "topicality": 0.94543207,
                },
                {
                    "mid": "/m/01ssh5",
                    "description": "Shoulder",
                    "score": 0.9439773,
                    "topicality": 0.9439773,
                },
                {
                    "mid": "/m/083jv",
                    "description": "White",
                    "score": 0.921867,
                    "topicality": 0.921867,
                },
                {
                    "mid": "/m/04_fs",
                    "description": "Muscle",
                    "score": 0.92062616,
                    "topicality": 0.92062616,
                },
                {
                    "mid": "/m/0dzd8",
                    "description": "Neck",
                    "score": 0.89153653,
                    "topicality": 0.89153653,
                },
                {
                    "mid": "/m/02p0tk3",
                    "description": "Human body",
                    "score": 0.88456863,
                    "topicality": 0.88456863,
                },
                {
                    "mid": "/m/062581",
                    "description": "Sleeve",
                    "score": 0.8724505,
                    "topicality": 0.8724505,
                },
                {
                    "mid": "/m/0244x1",
                    "description": "Gesture",
                    "score": 0.85260487,
                    "topicality": 0.85260487,
                },
                {
                    "mid": "/m/036k5h",
                    "description": "Grey",
                    "score": 0.8453826,
                    "topicality": 0.8453826,
                },
            ],
            "objects": {},
            "logos": {},
        },
    ),
    (
        "Person",
        {
            "labels": [
                {
                    "mid": "/m/01dvt1",
                    "description": "Joint",
                    "score": 0.97631377,
                    "topicality": 0.97631377,
                },
                {
                    "mid": "/m/035r7c",
                    "description": "Leg",
                    "score": 0.9196472,
                    "topicality": 0.9196472,
                },
                {
                    "mid": "/m/06hwcd",
                    "description": "Dress shirt",
                    "score": 0.89317924,
                    "topicality": 0.89317924,
                },
                {
                    "mid": "/m/0dzd8",
                    "description": "Neck",
                    "score": 0.87835157,
                    "topicality": 0.87835157,
                },
                {
                    "mid": "/m/062581",
                    "description": "Sleeve",
                    "score": 0.8724505,
                    "topicality": 0.8724505,
                },
                {
                    "mid": "/m/031974",
                    "description": "Waist",
                    "score": 0.8611735,
                    "topicality": 0.8611735,
                },
                {
                    "mid": "/m/0244x1",
                    "description": "Gesture",
                    "score": 0.85260487,
                    "topicality": 0.85260487,
                },
                {
                    "mid": "/m/036k5h",
                    "description": "Grey",
                    "score": 0.84286696,
                    "topicality": 0.84286696,
                },
                {
                    "mid": "/m/01vm1p",
                    "description": "Elbow",
                    "score": 0.8159894,
                    "topicality": 0.8159894,
                },
                {
                    "mid": "/m/025xryy",
                    "description": "Sportswear",
                    "score": 0.8118334,
                    "topicality": 0.8118334,
                },
            ],
            "objects": {},
            "logos": {},
        },
    ),
    (
        "Hat",
        {
            "labels": [
                {
                    "mid": "/m/062581",
                    "description": "Sleeve",
                    "score": 0.8724502,
                    "topicality": 0.8724502,
                },
                {
                    "mid": "/m/031974",
                    "description": "Waist",
                    "score": 0.835405,
                    "topicality": 0.835405,
                },
                {
                    "mid": "/m/04xz_5",
                    "description": "Blazer",
                    "score": 0.7796348,
                    "topicality": 0.7796348,
                },
                {
                    "mid": "/m/03gq5hm",
                    "description": "Font",
                    "score": 0.70676553,
                    "topicality": 0.70676553,
                },
                {
                    "mid": "/m/01j04m",
                    "description": "Thigh",
                    "score": 0.6920995,
                    "topicality": 0.6920995,
                },
                {
                    "mid": "/m/02vwbzz",
                    "description": "Electric blue",
                    "score": 0.6907393,
                    "topicality": 0.6907393,
                },
                {
                    "mid": "/m/02w3_2",
                    "description": "Formal wear",
                    "score": 0.68808895,
                    "topicality": 0.68808895,
                },
                {
                    "mid": "/m/0463sg",
                    "description": "Fashion accessory",
                    "score": 0.67012024,
                    "topicality": 0.67012024,
                },
                {
                    "mid": "/m/081pkj",
                    "description": "Event",
                    "score": 0.66124904,
                    "topicality": 0.66124904,
                },
                {
                    "mid": "/m/09w5r",
                    "description": "Human leg",
                    "score": 0.6398262,
                    "topicality": 0.6398262,
                },
            ],
            "objects": {},
            "logos": {},
        },
    ),
    (
        "Shoe",
        {
            "labels": [
                {
                    "mid": "/m/0244x1",
                    "description": "Gesture",
                    "score": 0.85259134,
                    "topicality": 0.85259134,
                },
                {
                    "mid": "/m/04k94",
                    "description": "Liquid",
                    "score": 0.7734446,
                    "topicality": 0.7734446,
                },
                {
                    "mid": "/m/09w5r",
                    "description": "Human leg",
                    "score": 0.68077403,
                    "topicality": 0.68077403,
                },
                {
                    "mid": "/m/0463sg",
                    "description": "Fashion accessory",
                    "score": 0.65503144,
                    "topicality": 0.65503144,
                },
                {
                    "mid": "/m/0cnmr",
                    "description": "Fur",
                    "score": 0.6385389,
                    "topicality": 0.6385389,
                },
                {
                    "mid": "/m/02vwbzz",
                    "description": "Electric blue",
                    "score": 0.608157,
                    "topicality": 0.608157,
                },
                {
                    "mid": "/m/031n1",
                    "description": "Foot",
                    "score": 0.54317236,
                    "topicality": 0.54317236,
                },
            ],
            "objects": {},
            "logos": {},
        },
    ),
]
